version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - cd website
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync ./build s3://$S3_ORIGIN_BUCKET/ --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"

artifacts:
  files:
    - 'build/**/*'
  name: BuildArtifact

cache:
  paths:
    - 'node_modules/**/*'
